Repository jenkinsci/pipeline-maven-plugin, pull requests merged in 2021-09, with the labels that each got.

#354 Ensure the H2 DB is shutdown on Jenkins termination
  jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
  jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginH2Dao.java
Labels: bug

#342 Fix layout of admin monitor
  jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/NonProductionGradeDatabaseWarningAdministrativeMonitor/message.jelly
Labels: bug

#347 Replace `MaskSecretsOutputStream` with standard `SecretPatterns`
  jenkins-plugin/pom.xml
  jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/console/MaskPasswordsConsoleLogFilter.java
  jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/console/MaskSecretsOutputStream.java
  jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisherTest.java
  pom.xml
Labels: enhancement

#362 [chore] Use the tidy:pom maven plugin to unify the project POMs
  jenkins-plugin/pom.xml
  maven-spy/pom.xml
  pom.xml
Labels: chore

#363 Bump Jenkins core requirement from 2.204.6 to 2.277.1
  jenkins-plugin/pom.xml
  pom.xml
Labels: dependencies

#344 [JENKINS-65800] Option to disable only fingerprint produced files or only archive
  README.adoc
  jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/GeneratedArtifactsPublisher.java
Labels: enhancement

#364 [JENKINS-66606] Add support for the Jenkins JUnit flaky-test-handler plugin
  README.adoc
  jenkins-plugin/pom.xml
  jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher.java
  jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisherTest.java
Labels: enhancement
