Repository jenkinsci/pipeline-maven-plugin, pull requests merged in 2022-11, with the labels that each got.

#551 Fix URL linking
  jenkins-plugin/pom.xml
Labels: documentation

#558 Use JUnitResultArchiver#parseAndSummarize method
  jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JunitTestsPublisher.java
Labels: enhancement

#559 chore: update baseline to 2.346
  jenkins-plugin/pom.xml
  jenkins-plugin/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
  jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/SqlTestsUtils.java
  pom.xml
Labels: dependencies, chore, java
