Repository jenkinsci/pipeline-maven-plugin, pull requests merged in 2022-01, with the labels that each got.

#398 [JENKINS-67507] Artifacts deployed by direct invocation of deploy-file goal don't trigger downstream builds
  jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/AbstractIntegrationTest.java
  jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyGraphTest.java
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_deployfile_base_project/pom.xml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_deployfile_dependency_project/pom.xml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_deployfile_dependency_project/src/main/java/com/example/App.java
  maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/JenkinsMavenEventSpy.java
  maven-spy/src/main/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/DeployDeployFileExecutionHandler.java
  maven-spy/src/test/java/org/jenkinsci/plugins/pipeline/maven/eventspy/handler/DeployDeployFileExecutionHandlerTest.java
Labels: enhancement

#402 Fix typo in the documentation of the withMaven step
  jenkins-plugin/src/main/resources/org/jenkinsci/plugins/pipeline/maven/WithMavenStep/help-maven.html
Labels: documentation

#405 cleanup POMs
  jenkins-plugin/pom.xml
  maven-spy/pom.xml
Labels: chore

#406 JENKINS-65001: add test for CasC
  jenkins-plugin/pom.xml
  jenkins-plugin/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeTest.java
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_default.yml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_mysql.yml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_postgresql.yml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_publishers.yml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_triggers.yml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_default.yml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_mysql.yml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_postgresql.yml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_publishers.yml
  jenkins-plugin/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_triggers.yml
Labels: chore
