Repository jenkinsci/pipeline-maven-plugin, pull requests merged in 2024-01, with the labels that each got.

#745 Replace deprecated Takari wrapper with official one in README
  FAQ.adoc
Labels: documentation

#749 fix JENKINS-72386: withMaven exits with unrecognized option --no-transfer-progress when using maven < 3.6.1
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersion.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersionUtils.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/MavenUtil.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersionTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersionUtilsTest.java
Labels: bug

#755 chore: temporarily pin `mysql` image to avoid test regressions
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeNeedDockerTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfigTest.java
Labels: dependencies

#758 fix JENKINS-72516: warning of unknown Maven version
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
Labels: bug
