Repository jenkinsci/pipeline-maven-plugin, pull requests merged in 2024-05, with the labels that each got.

#796 Set `safe.directory` in `WithMavenStepTest.tesWithDifferentJavasForBuild`
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
Labels: maintenance

#797 Replace deprecated Takari wrapper with official one
  FAQ.adoc
  README.adoc
Labels: documentation

#788 Revert to 1376.v18876d10ce9c detectWithContainer logic
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2Test.java
Labels: bug

#798 Adds support to detect Maven 4 beta versions
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersion.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersionUtils.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/MavenVersionUtilsTest.java
Labels: enhancement
