Repository jenkinsci/pipeline-maven-plugin, pull requests merged in 2024-03, with the labels that each got.

#766 Fix detection if withMaven is executed within container()
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
Labels: bug

#753 Reduce usage of Guice
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/cli/TriggerDownstreamPipelinesCommand.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncItemListener.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncRunListener.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListener.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DatabaseSyncRunListenerTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListenerTest.java
Labels: dependencies

#765 cleanup some dependencies not needed to be included in hpi
  pipeline-maven-api/pom.xml
  pipeline-maven-api/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenArtifact.java
  pipeline-maven-api/src/main/java/org/jenkinsci/plugins/pipeline/maven/dao/PipelineMavenPluginDao.java
  pipeline-maven-database/pom.xml
  pipeline-maven/pom.xml
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfig.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenSpyLogProcessor.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/NeededPipelineMavenDatabasePluginAdminMonitor.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesFingerprintPublisher.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/DependenciesLister.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/GeneratedArtifactsPublisher.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/TasksScannerPublisher.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/util/XmlUtils.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeNeedDockerTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepNoOptionalsTest.java
  pom.xml
Labels: dependencies

#751 [JENKINS-72529] write settings file always in UTF-8 encoding
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
Labels: bug

#764 JENKINS-59813 pipeline-maven JacocoPublisher handle excludes properly
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisher.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisherTest.java
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_with_jacoco_project/pom.xml
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/test/test_maven_projects/maven_jar_with_jacoco_project/src/main/java/com/example/exclude/MonoModuleMavenExcludeApp.java
Labels: bug

#770 Stop excluding ASM via the plugin system
  pipeline-maven/pom.xml
Labels: internal

#774 Drop detecting of execution inside container()
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
Labels: bug

#767 chore: switch to 2.414 baseline
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeNeedDockerTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/DependencyGraphTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfigTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepMavenExecResolutionTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/docker/JavaGitContainerTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/listeners/DownstreamPipelineTriggerRunListenerIntegrationTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/util/Conditions.java
  pom.xml
Labels: dependencies
