Repository jenkinsci/pipeline-maven-plugin, pull requests merged in 2025-03, with the labels that each got.

#878 chore: deploy all artifacts at the end of a release
  pom.xml
Labels: internal

#881 Removes Jacoco integration
  README.adoc
  pipeline-maven/pom.xml
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/MavenPublisherStrategy.java
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisher.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/MavenPublisherStrategyTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepGlobalConfigurationTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepOnMasterTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/publishers/JacocoReportPublisherTest.java
Labels: breaking

#884 do not use anymore fabricio docker-maven-plugin to build images with maven but use on the fly testcontainers
  pipeline-maven/pom.xml
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/AbstractIntegrationTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepMavenExecResolutionTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/docker/JavaGitContainerTest.java
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/Dockerfile
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/JavaGitContainer/Dockerfile
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/JavaMavenContainer/Dockerfile
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/JavaMavenWithMavenHomeContainer/Dockerfile
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/JavasContainer/Dockerfile
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/SshdContainer/unsafe
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/SshdContainer/unsafe.pub
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/SshdContainer/unsafe_enc_key
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/SshdContainer/unsafe_enc_key.pub
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/docker/SshdContainer/unsafe_enc_key_passphrase.txt
Labels: maintenance
