Repository jenkinsci/pipeline-maven-plugin, pull requests merged in 2025-06, with the labels that each got.

#911 chore: improve configuration coverage
  pipeline-maven/pom.xml
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStep.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/ConfigurationAsCodeTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/GlobalPipelineMavenConfigTest.java
  pipeline-maven/src/test/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepTest.java
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/configuration-as-code_publishers.yml
  pipeline-maven/src/test/resources/org/jenkinsci/plugins/pipeline/maven/expected_output_publishers.yml
Labels: chore, test

#912 JENKINS-72516 fix WARNING: You are running an old version of Maven
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/WithMavenStepExecution2.java
Labels: bug

#915 Consume symbols from API plugin
  pipeline-maven-api/pom.xml
  pipeline-maven/src/main/java/org/jenkinsci/plugins/pipeline/maven/publishers/MavenReport.java
  pipeline-maven/src/main/resources/images/symbols/apache-maven-icon.svg
  pipeline-maven/src/main/resources/images/symbols/apache-maven-rectangle.svg
  pipeline-maven/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/MavenReport/jobMain.jelly
  pipeline-maven/src/main/resources/org/jenkinsci/plugins/pipeline/maven/publishers/MavenReport/summary.jelly
Labels: enhancement
